# ~/.config/starship.toml

# Use custom format
format = """
[┌───────────────────>](bold green)
[│](bold green)$all
[└─$character](bold green) """
# Wait 10 milliseconds for starship to check files under the current directory.

scan_timeout = 10

command_timeout=10


[username]
style_user ="bold red"
show_always = true

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "


[line_break]
disabled = true

[custom]
disable=true
